/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oz.common.util;

public class MessageUtils {
    public static String getMessage() {
        return "Hello World!";
    }
    public static String getMessage2() {
        return "Hello World?";
    }
}
